config/routes.rb
Rails.application.routes.draw do
  resources :animals
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'statics#index'
  #generates /sightings/get_events route
    resources :sightings do
      get :get_events, on: :collection
    end

end

app/models/animal.rb
class Animal < ApplicationRecord
  has_many :sightings 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sighting.rb
class Sighting < ApplicationRecord
  belongs_to :animal
end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animal, only: [:show, :edit, :update, :destroy]

  # GET /animals
  # GET /animals.json
  def index
    @animals = Animal.all
  end

  # GET /animals/1
  # GET /animals/1.json
  def show
  end

  # GET /animals/new
  def new
    @animal = Animal.new
  end

  # GET /animals/1/edit
  def edit
  end

  # POST /animals
  # POST /animals.json
  def create
    @animal = Animal.new(animal_params)

    respond_to do |format|
      if @animal.save
        format.html { redirect_to @animal, notice: 'Animal was successfully created.' }
        format.json { render :show, status: :created, location: @animal }
      else
        format.html { render :new }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /animals/1
  # PATCH/PUT /animals/1.json
  def update
    respond_to do |format|
      if @animal.update(animal_params)
        format.html { redirect_to @animal, notice: 'Animal was successfully updated.' }
        format.json { render :show, status: :ok, location: @animal }
      else
        format.html { render :edit }
        format.json { render json: @animal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /animals/1
  # DELETE /animals/1.json
  def destroy
    @animal.destroy
    respond_to do |format|
      format.html { redirect_to animals_url, notice: 'Animal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_animal
      @animal = Animal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def animal_params
      params.require(:animal).permit(:common_name, :latin_name, :kingdom)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/sightings_controller.rb
class SightingsController < ApplicationController
  before_action :set_sighting, only: [:show, :edit, :update, :destroy]

  def get_events
    @sightings = Sighting.all
    events = []
    @sightings.each do |sighting|
      events << { id: sighting.id, title: sighting.animal.common_name, start: sighting.date, end: sighting.time, url: Rails.application.routes.url_helpers.sighting_path(sighting.id)}
    end
    render :json => events.to_json
  end

  # GET /sightings
  # GET /sightings.json
  def index
    @sightings = Sighting.all
    # if params[:start_date].empty? || params[:end_date].empty?
    #
    #
    # else
      # @sightings = Sighting.where(date: params[:start_date]..params[:end_date])
      # render('sightings/index.html.erb')
    # end
  end

  # GET /sightings/1
  # GET /sightings/1.json
  def show
  end

  # GET /sightings/new
  def new
    @sighting = Sighting.new
    @region = ['North', 'South', 'East', 'West']
    @animals_for_select = Animal.all.map do |animal|
      [animal.common_name, animal.id]
    end
    @region_for_select = @region.map do |region|
      [region, region]
    end
  end

  # GET /sightings/1/edit
  def edit
    @animals_for_select = Animal.all.map do |animal|
      [animal.common_name, animal.id]
    end
    @region = ['North','South', 'East', 'West']
    @region_for_select = @region.map do |region|
       [region, region]
    end
  end

  # POST /sightings
  # POST /sightings.json
  def create
    @sighting = Sighting.new(sighting_params)
    @region = ['North','South', 'East', 'West']
    @region_for_select = @region.map do |region|
      [region, region]
    end

    @animals_for_select = Animal.all.map do |animal|
      [animal.common_name, animal.id]
    end

    respond_to do |format|
      if @sighting.save
        format.html { redirect_to @sighting, notice: 'Sighting was successfully created.' }
        format.json { render :show, status: :created, location: @sighting }
      else
        format.html { render :new }
        format.json { render json: @sighting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /sightings/1
  # PATCH/PUT /sightings/1.json
  def update
    respond_to do |format|
      if @sighting.update(sighting_params)
        format.html { redirect_to @sighting, notice: 'Sighting was successfully updated.' }
        format.json { render :show, status: :ok, location: @sighting }
      else
        format.html { render :edit }
        format.json { render json: @sighting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /sightings/1
  # DELETE /sightings/1.json
  def destroy
    @sighting.destroy
    respond_to do |format|
      format.html { redirect_to sightings_url, notice: 'Sighting was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sighting
      @sighting = Sighting.find(params[:id])
    end



    # Never trust parameters from the scary internet, only allow the white list through.
    def sighting_params
      params.require(:sighting).permit(:date, :time, :latitude, :longitude, :animal_id, :region, :start_date, :end_date)
    end
end

app/controllers/statics_controller.rb
class StaticsController < ApplicationController
  def index
  end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sightings_helper.rb
module SightingsHelper
end

app/helpers/statics_helper.rb
module StaticsHelper
end

app/views/animals/_form.html.erb
<%= form_with(model: animal, local: true) do |form| %>
  <% if animal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(animal.errors.count, "error") %> prohibited this animal from being saved:</h2>

      <ul>
      <% animal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :common_name %>
    <%= form.text_field :common_name, id: :animal_common_name %>
  </div>

  <div class="field">
    <%= form.label :latin_name %>
    <%= form.text_field :latin_name, id: :animal_latin_name %>
  </div>

  <div class="field">
    <%= form.label :kingdom %>
    <%= form.text_field :kingdom, id: :animal_kingdom %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/animals/edit.html.erb
<h1>Editing Animal</h1>

<%= render 'form', animal: @animal %>

<%= link_to 'Show', @animal %> |
<%= link_to 'Back', animals_path %>

app/views/animals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Animals</h1>

<table>
  <thead>
    <tr>
      <th>Common name</th>
      <th>Latin name</th>
      <th>Kingdom</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="animal_list">
    <% @animals.each do |animal| %>
      <tr>
        <td><%= animal.common_name %></td>
        <td><%= animal.latin_name %></td>
        <td><%= animal.kingdom %></td>
        <td><%= link_to 'Show', animal %></td>
        <td><%= link_to 'Edit', edit_animal_path(animal) %></td>
        <td><%= link_to 'Destroy', animal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<p>
 <!-- Input area for new wine -->
  <div class="field">
   <label for="common_name">Common Name</label><br>
   <input type="text" name="animal[common_name]" id="animal_common_name" />
 </div>
 <div class="field">
   <label for="latin_name">Latin Name</label><br>
   <input type="text" name="animal[latin_name]" id="animal_latin_name" />
 </div>
 <div class="field">
   <label for="kingdom">Kingdom</label><br>
   <input type="text" name="animal[kingdom]" id="animal_kingdom" />
 </div>
 <button id="add_new_animal_button">Add New Animal</button>
</p>

<%#= link_to 'New Animal', new_animal_path %>

app/views/animals/new.html.erb
<h1>New Animal</h1>

<%= render 'form', animal: @animal %>

<%= link_to 'Back', animals_path %>

app/views/animals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Common name:</strong>
  <%= @animal.common_name %>
</p>

<p>
  <strong>Latin name:</strong>
  <%= @animal.latin_name %>
</p>

<p>
  <strong>Kingdom:</strong>
  <%= @animal.kingdom %>
</p>

<p>
  <strong> Sightings </strong>
  <ul>
    <% @animal.sightings.each do |sighting| %>
        <li>
            <%= sighting.date %>, lat/long: <%= sighting.latitude %>, <%= sighting.longitude %>
        </li>
    <% end %>
  </ul>
</p>
<a href="/sightings/new">Add a new sighting here</a>
<br>
<%= link_to 'Edit', edit_animal_path(@animal) %> |
<%= link_to 'Back', animals_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WildlifeTracker</title>


    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'jquery', 'application', 'data-turbolinks-track': 'reload' %>
    
    <!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sightings/_form.html.erb
<%= form_with(model: sighting, local: true) do |form| %>
  <% if sighting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sighting.errors.count, "error") %> prohibited this sighting from being saved:</h2>

      <ul>
      <% sighting.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :date %>
    <%= form.date_select :date, id: :sighting_date %>
  </div>

  <div class="field">
    <%= form.label :time %>
    <%= form.time_select :time, id: :sighting_time %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude, id: :sighting_latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude, id: :sighting_longitude %>
  </div>

  <div class="field">
    <%= form.label :region %>
    <%= select(:sighting, :region, @region_for_select) %>
  </div>

  <div class="field">
    <%= form.label :animal_id %>
    <%= select(:sighting, :animal_id, @animals_for_select) %>

  </div>

  <div class="actions">
    <%= form.submit  %>
  </div>
<% end %>

app/views/sightings/edit.html.erb
<h1>Editing Sighting</h1>

<%= render 'form', sighting: @sighting %>

<%= link_to 'Show', @sighting %> |
<%= link_to 'Back', sightings_path %>

app/views/sightings/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sightings</h1>

<div id="calendar"></div>


<table>
  <thead>
    <tr>
      <th>Date</th>
      <th>Time</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th>Region</th>
      <th>Animal</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody id="sighting_list">
    <% @sightings.each do |sighting| %>
      <tr>
        <td><%= sighting.date %></td>
        <td><%= sighting.time %></td>
        <td><%= sighting.latitude %></td>
        <td><%= sighting.longitude %></td>
        <td><%= sighting.region %></td>
        <td><%= sighting.animal.common_name %></td>
        <td><%= link_to 'Show', sighting %></td>
        <td><%= link_to 'Edit', edit_sighting_path(sighting) %></td>
        <td><%= link_to 'Destroy', sighting, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

 <p>

   <div class="field">
    <label for="date">Date</label><br>
    <input type="date" name="sighting[date]" id="sighting_date" />
  </div>
  <div class="field">
    <label for="time">Time</label><br>
    <input type="time" name="sighting[time]" id="sighting_time" />
  </div>
  <div class="field">
    <label for="latitude">Latitude</label><br>
    <input type="text" name="sighting[latitude]" id="sighting_latitude" />
  </div>
  <div class="field">
    <label for="longitude">longitude</label><br>
    <input type="text" name="sighting[longitude]" id="sighting_longitude" />
  </div>
  <div class="field">
    <label for="region">Region</label><br>
    <select id="sighting_region" name="sighting[region]">
      <option value="North">North</option>
      <option value="South">South</option>
      <option value="East">East</option>
      <option value="West">West</option>
    </select>
  </div>
   <div class="field">
    <label for="Animal">Animal</label><br>
    <select id="sighting_animal" name="sighting[animal]">
      <option> 1 </option>
      <option> 2 </option>

    </select>


      <button id="add_new_sighting_button"> Add New Sighting </button>
  </div>
</p>



<%= link_to 'New Sighting', new_sighting_path %>

app/views/sightings/new.html.erb
<body id = "new-sighting">

<div class="container ">

<h1>Sightings</h1>

<div class="row">

    <div class="col-sm-6 new-sighting">
        <h2>Report a sighting</h2>
    <%= render 'form', sighting: @sighting %>
    </div>

    <div class="col-sm-6 new-sighting">
        <h2>See sightings</h2>
        <form action="/sightings" method="get">
            <label for="start_date">Start date</label>
            <input id="start_date" name="start_date" type="date" >
            <label for="end_date">End date</label>
            <input id="end_date" name="end_date" type="date" >
            <br><br>
            <button>See sightings</button>
        </form>
        <%= image_tag "bird.png", class: "animals", id: "bird"%>

    </div>

</div>

<div class="row link-at-bottom">
    <a href="/">Home</a>
    <a href="/animals/new">Add an animal</a>

</div>


</div>



</body>

app/views/sightings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @sighting.date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @sighting.time %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @sighting.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @sighting.longitude %>
</p>

<p>
  <strong>Region:</strong>
  <%= @sighting.region %>
</p>

<p>
  <strong>Animal:</strong>
  <%= @sighting.animal.common_name %>
</p>

<%= link_to 'Edit', edit_sighting_path(@sighting) %> |
<%= link_to 'Back', sightings_path %>

app/views/statics/index.html.erb
<head>
  <link href="https://fonts.googleapis.com/css?family=Open+Sans|Roboto" rel="stylesheet">
  <link href="https://fonts.googleapis.com/css?family=Lato|Montserrat|Open+Sans|Oswald|Raleway" rel="stylesheet">
</head>


<div class="container homepage">
  <h1>Wildlife Tracker</h1>

  <div class="row">
    <div class="col-sm-6 new-sighting">
      <a href="/sightings/new">Report a Sighting</a>
    </div>

      <div class="col-sm-6 statics-index">
        <a href="animals#create">Add an animal</a>
      </div>
   </div>

   <div class="row">
     <div class="col-sm-6 new-sighting">
     <%= image_tag "binoculars.png", class: "spyglass", id: "binoculars"%>
     </div>

       <div class="col-sm-6 new-sighting">
         <%= image_tag "fox.png", class: "animal", id: "fox" %>
       </div>
    </div>


</div>

<!-- <img src="images/fox.png" alt="fox" style="width:304px;height:228px;"> -->


<!-- <form action="/sightings" method="get">
  <label for="start_date">Start date</label>
  <input id="start_date" name="start_date" type="date">
  <label for="end_date">End date</label>
  <input id="end_date" name="end_date" type="date">
  <button>Run report</button>
</form> -->